//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wi_Fi_Monitor.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wi_Fi_Monitor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;WLANProfile xmlns=&quot;http://www.microsoft.com/networking/WLAN/profile/v1&quot;&gt;
        ///  &lt;name&gt;{0}&lt;/name&gt;
        ///  &lt;SSIDConfig&gt;
        ///    &lt;SSID&gt;
        ///      &lt;name&gt;{0}&lt;/name&gt;
        ///		&lt;/SSID&gt;
        ///	&lt;/SSIDConfig&gt;
        ///	&lt;connectionType&gt;ESS&lt;/connectionType&gt;
        ///	&lt;connectionMode&gt;manual&lt;/connectionMode&gt;
        ///	&lt;MSM&gt;
        ///		&lt;security&gt;
        ///			&lt;authEncryption&gt;
        ///        &lt;authentication&gt;{1}&lt;/authentication&gt;
        ///        &lt;encryption&gt;{2}&lt;/encryption&gt;
        ///				&lt;useOneX&gt;false&lt;/useOneX&gt;
        ///			&lt;/authEncryption&gt;
        ///		&lt;/security&gt;
        ///	&lt;/MSM&gt;
        ///&lt;/WLANProfile&gt;
        ///.
        /// </summary>
        internal static string OPEN {
            get {
                return ResourceManager.GetString("OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;WLANProfile xmlns=&quot;http://www.microsoft.com/networking/WLAN/profile/v1&quot;&gt;
        ///  &lt;name&gt;{0}&lt;/name&gt;
        ///  &lt;SSIDConfig&gt;
        ///    &lt;SSID&gt;
        ///      &lt;name&gt;{0}&lt;/name&gt;
        ///		&lt;/SSID&gt;
        ///	&lt;/SSIDConfig&gt;
        ///	&lt;connectionType&gt;ESS&lt;/connectionType&gt;
        ///	&lt;connectionMode&gt;manual&lt;/connectionMode&gt;
        ///	&lt;MSM&gt;
        ///		&lt;security&gt;
        ///			&lt;authEncryption&gt;
        ///        &lt;authentication&gt;{1}&lt;/authentication&gt;
        ///        &lt;encryption&gt;{2}&lt;/encryption&gt;
        ///        &lt;useOneX&gt;false&lt;/useOneX&gt;
        ///			&lt;/authEncryption&gt;
        ///			&lt;sharedKey&gt;
        ///				&lt;protected&gt;false&lt;/protected&gt;
        ///        &lt;keyMaterial&gt;{3} [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string WEP {
            get {
                return ResourceManager.GetString("WEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;WLANProfile xmlns=&quot;http://www.microsoft.com/networking/WLAN/profile/v1&quot;&gt;
        ///	&lt;name&gt;GoproNumber14&lt;/name&gt;
        ///	&lt;SSIDConfig&gt;
        ///		&lt;SSID&gt;
        ///			&lt;name&gt;{0}&lt;/name&gt;
        ///		&lt;/SSID&gt;
        ///		&lt;nonBroadcast&gt;true&lt;/nonBroadcast&gt;
        ///	&lt;/SSIDConfig&gt;
        ///	&lt;connectionType&gt;ESS&lt;/connectionType&gt;
        ///	&lt;connectionMode&gt;auto&lt;/connectionMode&gt;
        ///	&lt;MSM&gt;
        ///		&lt;security&gt;
        ///			&lt;authEncryption&gt;
        ///				&lt;authentication&gt;{1}&lt;/authentication&gt;
        ///				&lt;encryption&gt;AES&lt;/encryption&gt;
        ///				&lt;useOneX&gt;false&lt;/useOneX&gt;
        ///			&lt;/authEncryption&gt;
        ///			&lt;sharedKey&gt;
        ///				&lt;keyT [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string WPA2PSK {
            get {
                return ResourceManager.GetString("WPA2PSK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;WLANProfile xmlns=&quot;http://www.microsoft.com/networking/WLAN/profile/v1&quot;&gt;
        ///	&lt;name&gt;{0}&lt;/name&gt;
        ///	&lt;SSIDConfig&gt;
        ///		&lt;SSID&gt;
        ///			&lt;name&gt;{0}&lt;/name&gt;
        ///		&lt;/SSID&gt;
        ///	&lt;/SSIDConfig&gt;
        ///	&lt;connectionType&gt;ESS&lt;/connectionType&gt;
        ///	&lt;connectionMode&gt;manual&lt;/connectionMode&gt;
        ///	&lt;MSM&gt;
        ///		&lt;security&gt;
        ///			&lt;authEncryption&gt;
        ///				&lt;authentication&gt;{1}&lt;/authentication&gt;
        ///				&lt;encryption&gt;{2}&lt;/encryption&gt;
        ///				&lt;useOneX&gt;false&lt;/useOneX&gt;
        ///			&lt;/authEncryption&gt;
        ///			&lt;sharedKey&gt;
        ///				&lt;keyType&gt;passPhrase&lt;/keyType&gt;
        ///				&lt;protected&gt;fals [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string WPAPSK {
            get {
                return ResourceManager.GetString("WPAPSK", resourceCulture);
            }
        }
    }
}
